{% set version = "2.29" %}

package:
  name: graph-tool
  version: {{ version }}

source:
  git_url: https://git.skewed.de/count0/graph-tool
  git_tag: release-{{ version }}

build:
  skip: true  # [win]
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - pkg-config

    #- {{ compiler("cxx") }}
    - clangxx_osx-64=8.*  # [osx]
    - gxx_linux-64=8.*    # [linux]
    
  host:
    - python
    - numpy
    - boost
    - expat
    - scipy >=1.0
    - cgal 4.14*
    - sparsehash 2.0.*
    - cairomm
    - pycairo
    
  run:
    - python
    - boost
    - expat
    - scipy >=1.0
    - {{ pin_compatible('numpy') }}
    - cgal >=4.14
    - sparsehash >=2.0
    - cairomm
    - pycairo

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  home: https://graph-tool.skewed.de/
  license: GPLv3
  license_file: LICENSE
  summary: Efficient network analysis

extra:
  recipe-maintainers:
    - stuarteberg
