{% set version = "2.29" %}

package:
  name: graph-tool
  version: {{ version }}

source:
  # We pull from git (rather than tarball)
  # so we can run autotools ourselves.
  # This avoids a configure problem on mac, and makes the
  # configure script slightly more straightforward to patch.
  git_url: https://git.skewed.de/count0/graph-tool
  git_tag: release-{{ version }}

  patches:
    - patches/no-check-python-link.patch
    - patches/skip-boost-python-config.patch
    
    # These implement a workaround for a bug in clang,
    # which will probably be added to master in version 2.30
    # See the following merge request:
    # https://git.skewed.de/count0/graph-tool/merge_requests/19
    - patches/no-max-element-graph-adjacency.patch  # [osx]
    - patches/no-max-element-graph-blockmodel.patch # [osx]

build:
  skip: true  # [win or py != 37]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - pkg-config

    # On mac, requires clang 8
    # (clang 4 does not have sufficient c++17 support)
    - clangxx_osx-64 >=8*  # [osx]
    - {{ compiler("cxx") }} # [linux]
    
  host:
    - python
    - numpy
    - boost
    - expat
    - scipy >=1.0
    - cgal 4.14*
    - sparsehash 2.0*
    - cairomm
    - pycairo
    
  run:
    - python
    - boost
    - expat
    - scipy >=1.0
    - {{ pin_compatible('numpy') }}
    - cgal >=4.14
    - sparsehash >=2.0
    - cairomm
    - pycairo

test:
  imports:
    - graph_tool
    - graph_tool.all

about:
  home: https://graph-tool.skewed.de/
  license: GPLv3
  license_file: LICENSE
  summary: Efficient network analysis

extra:
  recipe-maintainers:
    - stuarteberg
