travis:
  secure:
    BINSTAR_TOKEN: jLBWWovr+x71edHrQ3qLJzYpJhUJofjmU9cAWNsrgyuB0ii8uc5Zc6ZYNXi6XCOrG1oEmVdoPbMeemoKbhSOfRRujWadnIwPB8nbl3KWOKJniTelz8nxIiLQrzjS6IYAhoPhEEgr7pPGtTnOS7lJr5Tw8tutpa5uCatOdiQeANkh0oQC4vHXmPdVhV9DThwZkoT0xkgqp+Fmpza7osMROWZi3vMPSXlw4zxfl4lBfwjq3U0EYFo6hpdq9RH+44rnmlntU3nu1k9cfsBdEhebfEAgE+hYxi0KW7injCYm5+0DB2/Ba63L/sjA4mg9pt+2AmDgkBy1CI3DINzpTw/jSrw9ja9b8Jw33i9JW4A5T2BoW77ltOzvWsiUV43R4xtOaHe+IFaMx7YaPHhFfNr01nuBqBpLSDfI/xGlVNcfrVYz9qj0ZVKEn68peAyeXpN7lX1wUL/UMuKMb+xh/ykTbmvloLZVx21hcCffZcCkjNImVeO+hRbQ4mAE4JuzeZ+mUxuXr6pyGC4mBoYDcbIjQx0KhDsMjX5ciu698HsyqNUOKK5H502Gvfrw74SdXKe0k+o8ldkzFhIzvG/i2pVtUyBP7yRW7fP//Y2bfOmv2KK+QnhgOzXrX1DXJrXp44URKcLMm4W4m8Ze6dHTmA2Dx3cxD8Z+51vuBdbzx3BzqTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
